#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Aug 10 18:07:03 CST 2026
maven-metadata-registry.quarkus.io.xml.lastUpdated=1786356423908
