#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Aug 17 11:26:16 CST 2026
maven-metadata-apache-public-repository-group.xml.error=
maven-metadata-apache-public-repository-group.xml.lastUpdated=1786937176952
maven-metadata-apache-snapshot-repository-group.xml.error=
maven-metadata-apache-snapshot-repository-group.xml.lastUpdated=1786937176952
maven-metadata-central.xml.error=
maven-metadata-central.xml.lastUpdated=1786937176932
